// Code generated by turbopuffer-apigen. DO NOT EDIT.

import { Bm25ClauseParams } from '../index';
import { ContainsAllTokensFilterParams } from '../index';
import { ContainsAnyTokenFilterParams } from '../index';
import { DecayParams } from '../index';
import { EmbedParams } from '../index';
import { FuzzyParams } from '../index';
import { RrfParams } from '../index';
import { SaturateParams } from '../index';

export type AggregateBy<T = Record<string, any>> =
  | ['Count']
  | ['Sum', keyof T & string]
  | ['Count', keyof T & string];
export type Expr<T = Record<string, any>> =
  | ExprRefNew<T>
  | ['Embed', string]
  | ['Embed', string, EmbedParams];
export type ExprRefNew<T = Record<string, any>> = { $ref_new: keyof T & string };
export type Filter<T = Record<string, any>> =
  | [keyof T & string, 'Eq', any]
  | [keyof T & string, 'NotEq', any]
  | [keyof T & string, 'In', any[]]
  | [keyof T & string, 'NotIn', any[]]
  | [keyof T & string, 'Contains', any]
  | [keyof T & string, 'NotContains', any]
  | [keyof T & string, 'ContainsAny', any[]]
  | [keyof T & string, 'NotContainsAny', any[]]
  | [keyof T & string, 'Lt', any]
  | [keyof T & string, 'Lte', any]
  | [keyof T & string, 'Gt', any]
  | [keyof T & string, 'Gte', any]
  | [keyof T & string, 'AnyLt', any]
  | [keyof T & string, 'AnyLte', any]
  | [keyof T & string, 'AnyGt', any]
  | [keyof T & string, 'AnyGte', any]
  | [keyof T & string, 'Glob', string]
  | [keyof T & string, 'NotGlob', string]
  | [keyof T & string, 'IGlob', string]
  | [keyof T & string, 'NotIGlob', string]
  | [keyof T & string, 'Regex', string]
  | [keyof T & string, 'Fuzzy', string, FuzzyParams]
  | [keyof T & string, 'ContainsAllTokens', string]
  | [keyof T & string, 'ContainsAllTokens', string[]]
  | [keyof T & string, 'ContainsAllTokens', string, ContainsAllTokensFilterParams]
  | [keyof T & string, 'ContainsAllTokens', string[], ContainsAllTokensFilterParams]
  | [keyof T & string, 'ContainsAnyToken', string]
  | [keyof T & string, 'ContainsAnyToken', string[]]
  | [keyof T & string, 'ContainsAnyToken', string, ContainsAnyTokenFilterParams]
  | [keyof T & string, 'ContainsAnyToken', string[], ContainsAnyTokenFilterParams]
  | [keyof T & string, 'ContainsTokenSequence', string]
  | [keyof T & string, 'ContainsTokenSequence', string[]]
  | ['Not', Filter<T>]
  | ['And', Filter<T>[]]
  | ['Or', Filter<T>[]];
export type GroupBy<T = Record<string, any>> = string | Record<string, GroupByFunction<T>>;
export type GroupByFunction<T = Record<string, any>> = ['ForEachUnique', keyof T & string];
export type RankBy<T = Record<string, any>> =
  | RankByAnn<T>
  | RankByAnnExpr<T>
  | RankByKnn<T>
  | RankByKnnExpr<T>
  | RankBySparseKnn<T>
  | RankByText<T>
  | RankByAttribute<T>
  | RankByAttributes<T>;
export type RankByAnn<T = Record<string, any>> = [keyof T & string, 'ANN', number[]];
export type RankByAnnExpr<T = Record<string, any>> = [keyof T & string, 'ANN', Expr<T>];
export type RankByAttribute<T = Record<string, any>> = [keyof T & string, RankByAttributeOrder<T>];
export type RankByAttributeOrder<T = Record<string, any>> = 'asc' | 'desc';
export type RankByAttributes<T = Record<string, any>> = RankByAttribute<T>[];
export type RankByKnn<T = Record<string, any>> = [keyof T & string, 'kNN', number[]];
export type RankByKnnExpr<T = Record<string, any>> = [keyof T & string, 'kNN', Expr<T>];
export type RankBySparseKnn<T = Record<string, any>> = [
  keyof T & string,
  'SparseKNN',
  Record<string, number>,
];
export type RankByText<T = Record<string, any>> =
  | [keyof T & string, 'BM25', string]
  | [keyof T & string, 'BM25', string[]]
  | [keyof T & string, 'BM25', string, Bm25ClauseParams]
  | [keyof T & string, 'BM25', string[], Bm25ClauseParams]
  | ['Sum', RankByText<T>[]]
  | ['Max', RankByText<T>[]]
  | ['Product', number, RankByText<T>]
  | ['Product', RankByText<T>, number]
  | Filter<T>
  | ['Attribute', keyof T & string]
  | ['Saturate', RankByText<T>, SaturateParams]
  | ['Decay', RankByText<T>, DecayParams]
  | ['Dist', RankByText<T>, any];
export type RerankBy<T = Record<string, any>> = ['RRF'] | ['RRF', RrfParams];
