// Code generated by turbopuffer-apigen. DO NOT EDIT.

import { Bm25ClauseParams } from '../index';
import { ContainsAllTokensFilterParams } from '../index';
import { ContainsAnyTokenFilterParams } from '../index';
import { DecayParams } from '../index';
import { SaturateParams } from '../index';

export type AggregateBy = ['Count'] | ['Sum', string] | ['Count', string];
export type Expr = ExprRefNew;
export type ExprRefNew = { $ref_new: string };
export type Filter<T = Record<string, any>> =
  | [keyof T & string, 'Eq', any]
  | [keyof T & string, 'NotEq', any]
  | [keyof T & string, 'In', any[]]
  | [keyof T & string, 'NotIn', any[]]
  | [keyof T & string, 'Contains', any]
  | [keyof T & string, 'NotContains', any]
  | [keyof T & string, 'ContainsAny', any[]]
  | [keyof T & string, 'NotContainsAny', any[]]
  | [keyof T & string, 'Lt', any]
  | [keyof T & string, 'Lte', any]
  | [keyof T & string, 'Gt', any]
  | [keyof T & string, 'Gte', any]
  | [keyof T & string, 'AnyLt', any]
  | [keyof T & string, 'AnyLte', any]
  | [keyof T & string, 'AnyGt', any]
  | [keyof T & string, 'AnyGte', any]
  | [keyof T & string, 'Glob', string]
  | [keyof T & string, 'NotGlob', string]
  | [keyof T & string, 'IGlob', string]
  | [keyof T & string, 'NotIGlob', string]
  | [keyof T & string, 'Regex', string]
  | [keyof T & string, 'ContainsAllTokens', string]
  | [keyof T & string, 'ContainsAllTokens', string[]]
  | [keyof T & string, 'ContainsAllTokens', string, ContainsAllTokensFilterParams]
  | [keyof T & string, 'ContainsAllTokens', string[], ContainsAllTokensFilterParams]
  | [keyof T & string, 'ContainsAnyToken', string]
  | [keyof T & string, 'ContainsAnyToken', string[]]
  | [keyof T & string, 'ContainsAnyToken', string, ContainsAnyTokenFilterParams]
  | [keyof T & string, 'ContainsAnyToken', string[], ContainsAnyTokenFilterParams]
  | [keyof T & string, 'ContainsTokenSequence', string]
  | [keyof T & string, 'ContainsTokenSequence', string[]]
  | ['Not', Filter<T>]
  | ['And', Filter<T>[]]
  | ['Or', Filter<T>[]];
export type RankBy = RankByVector | RankByKnn | RankByText | RankByAttribute | RankByAttributes;
export type RankByAttribute = [string, RankByAttributeOrder];
export type RankByAttributeOrder = 'asc' | 'desc';
export type RankByAttributes = RankByAttribute[];
export type RankByKnn = [string, 'kNN', number[]];
export type RankByText =
  | [string, 'BM25', string]
  | [string, 'BM25', string[]]
  | [string, 'BM25', string, Bm25ClauseParams]
  | [string, 'BM25', string[], Bm25ClauseParams]
  | ['Sum', RankByText[]]
  | ['Max', RankByText[]]
  | ['Product', number, RankByText]
  | ['Product', RankByText, number]
  | Filter
  | ['Attribute', string]
  | ['Saturate', RankByText, SaturateParams]
  | ['Decay', RankByText, DecayParams]
  | ['Dist', RankByText, any];
export type RankByVector = [string, 'ANN', number[]];
