configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-6fb4376a43d51aefbbd39b2d1ad924cea5af786c5e5e6de9d5aed6a594589c4b.yml
openapi_spec_hash: 84775addbf01ae183699a124ad0a7117
config_hash: fb4fcbea34061aefdc474bc42d366209
