#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

api_gen_image=ghcr.io/turbopuffer/turbopuffer-apigen:21900adc37f904eca6728878a01932c27920c315

echo "==> Generating code"
docker run -v "$(pwd):/work" "$api_gen_image" typescript > src/resources/custom.ts
