#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Checking for outdated supplemental generated code"
scripts/gen
if ! git diff --exit-code; then
    echo "error: supplemental generated code is out of date" >&2
    echo " hint: run \`scripts/gen\` to regenerate the code" >&2
    exit 1
fi

echo "==> Running eslint"
./node_modules/.bin/eslint .

echo "==> Building"
./scripts/build

echo "==> Checking types"
./node_modules/typescript/bin/tsc

echo "==> Running Are The Types Wrong?"
./node_modules/.bin/attw --pack dist -f json >.attw.json || true
node scripts/utils/attw-report.cjs

echo "==> Running publint"
./node_modules/.bin/publint dist
